name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        architecture: [x64]
        xml: [builtin]
        include:
          - python-version: "3.8"
            os: windows-latest
            architecture: x86
            xml: builtin
          - python-version: "3.x"
            os: windows-latest
            architecture: x64
            xml: defusedxml
          - python-version: "3.x"
            os: windows-latest
            architecture: x64
            xml: lxml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Set up Python ${{ matrix.python-version }} (non Windows)
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
      - name: Install numpy 1.23.5 (Windows, x86)
        if: ${{ matrix.architecture == 'x86' }}
        run: python -m pip install --upgrade numpy==1.23.5
      - name: Install package (and test dependencies)
        run: |
          python -m pip install --upgrade pytest pytest-cov
          python -m pip install --upgrade .[h5py,google] --prefer-binary
      - name: Install defusedxml
        if: ${{ matrix.xml == 'defusedxml' }}
        run: python -m pip install --upgrade defusedxml
      - name: Install lxml
        if: ${{ matrix.xml == 'lxml' }}
        run: python -m pip install --upgrade lxml
      - name: Run tests
        run: |
          python -c "from msl.io.readers._xlrd.xlsx import ET; print(ET)"
          python -m pytest
