name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 110

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows, ubuntu, macos]
        architecture: [x64]
        xml: [builtin]
        include:
          - python-version: "3.x"
            os: windows
            architecture: x86
            xml: builtin
          - python-version: "3.x"
            os: windows
            architecture: x64
            xml: defusedxml
          - python-version: "3.x"
            os: windows
            architecture: x64
            xml: lxml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies and package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade --editable .[tests]
      - name: Install defusedxml
        if: ${{ matrix.xml == 'defusedxml' }}
        run: python -m pip install --upgrade defusedxml
      - name: Install lxml
        if: ${{ matrix.xml == 'lxml' }}
        run: python -m pip install --upgrade lxml
      - name: Run tests
        run: |
          python -c "from msl.io.readers._xlrd.xlsx import ET; print(ET)"
          python -m pytest
